# Sync docs/PROTOCOL.md -> jetson/docs/PROTOCOL.md
# Chạy mỗi khi cập nhật PROTOCOL để 2 bản không drift.
#
# Usage (từ repo root):
#   pwsh scripts/sync_protocol.ps1

param(
    [string]$Source = "docs/PROTOCOL.md",
    [string]$Dest   = "jetson/docs/PROTOCOL.md"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $Source)) {
    Write-Error "Source not found: $Source"
    exit 1
}

$destDir = Split-Path -Parent $Dest
if (-not (Test-Path $destDir)) {
    New-Item -ItemType Directory -Path $destDir -Force | Out-Null
}

$header = @"
<!--
  AUTO-GENERATED COPY. Do not edit this file directly.
  Source of truth: /docs/PROTOCOL.md
  Run: pwsh scripts/sync_protocol.ps1
-->

"@

$content = Get-Content -Path $Source -Raw
Set-Content -Path $Dest -Value ($header + $content) -NoNewline

Write-Host "[sync_protocol] $Source -> $Dest" -ForegroundColor Green
